### ISSUE TITLE
Manapool disconnect

### ISSUE THREAD

**Issue by brachy84** [Tawling/Morechids#12]
When i unload the chunk (travel some hundred blocks) the morechid gets disconnected from Manapool. This can be fixed by chunk loading the chunk via FTB Utils. But when i leave the world and then join it disconnects to even when chunk loaded. 
Pls fix

**Comment by lucidobservor** [comment]
This has in fact already been fixed in GitHub. If you download this repo and build the mod manually, you'll end up with a JAR that doesn't have this issue. Unfortunately, the version of the mod of CurseForge is still a few bugfixes behind the master branch of this repo.

**Comment by Tawling** [comment]
This is now fixed in the latest version available on CurseForge.
