### ISSUE TITLE
Custom Orechids ignore metadata

### ISSUE THREAD

**Issue by MightyBidoof** [Tawling/Morechids#8]
Title says it all

`//Tier 2 Orechid
var tierTwo = mods.morechids.Registry.getFlower("orechid_ores_metal");
//Orechid Ores
tierTwo.addRecipe(<minecraft:stone>, <thermalfoundation:ore>, 60);
tierTwo.addRecipe(<minecraft:stone>, <thermalfoundation:ore:1>, 60);
tierTwo.addRecipe(<minecraft:stone>, <thermalfoundation:ore:2>, 55);
tierTwo.addRecipe(<minecraft:stone>, <thermalfoundation:ore:3>, 55);
tierTwo.addRecipe(<minecraft:stone>, <thermalfoundation:ore:4>, 55);
tierTwo.addRecipe(<minecraft:stone>, <thermalfoundation:ore:5>, 50);
tierTwo.addRecipe(<minecraft:stone>, <thaumcraft:ore_quartz>, 45);
tierTwo.addRecipe(<minecraft:stone>, <minecraft:gold_ore>, 45);
tierTwo.addRecipe(<minecraft:stone>, <thaumcraft:ore_cinnabar>, 30);
tierTwo.addRecipe(<minecraft:stone>, <thaumcraft:ore_amber>, 30);
tierTwo.addRecipe(<minecraft:stone>, <minecraft:emerald_ore>, 15);`

this script should generate 6 different ores from thermal expansion, along with a few other ores, slightly weighted towards copper, this displays normally in JEI.

instead, this is the result when the orechid is active
![image1](https://user-images.githubusercontent.com/12218253/50363780-1f829c80-0565-11e9-90d8-ddd06fb8f749.png)

**Comment by Tawling** [comment]
This should now be fixed in the latest version 1.3.0 now available on CurseForge. Apologies for the huge delay!
